"""Re-add category column as list of enums

Revision ID: 0bda50c93235
Revises: cca5d59cab30
Create Date: 2025-10-22 23:47:04.056086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bda50c93235'
down_revision = 'cca5d59cab30'
branch_labels = None
depends_on = None


def upgrade():
     # Create the category enum type first
    category_enum = postgresql.ENUM(
        'STEM_Education', 'Math_and_Science_Education', 'Career_and_Technical_Education', 
        'Special_Education', 'Early_Childhood_Education', 'Teacher_Professional_Development', 
        'Leadership_and_Administration_Development', 'Social_Emotional_Learning', 
        'School_Climate_and_Culture', 'Bullying_Prevention', 'School_Safety_and_Security', 
        'Digital_Literacy_and_Technology', 'Educational_Technology_Innovation', 
        'After_School_Programs', 'Arts_and_Music_Education', 'Environmental_Education', 
        'Health_and_Wellness', 'Nutrition_and_School_Meals', 'Student_Mental_Health', 
        'Equity_and_Inclusion', 'Community_Engagement', 'Parental_Involvement', 
        'College_and_Career_Readiness', 'Civic_and_History_Education', 'English_Language_Learners', 
        'Financial_Literacy', 'Educational_Research_and_Innovation', 'Facilities_and_Infrastructure', 
        'Data_and_Assessment_Initiatives', 'Transportation_and_Accessibility', 'Other', 
        name='opportunity_category_enum'
    )
    category_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', postgresql.ARRAY(category_enum), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('category')
    # ### end Alembic commands ###
