"""Removed not null constraint on source_grant_id column

Revision ID: 0f999a6d2e4a
Revises: 0bda50c93235
Create Date: 2025-10-23 21:55:21.067720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f999a6d2e4a'
down_revision = '0bda50c93235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('source_grant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.alter_column('source_grant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
