"""Detect all models

Revision ID: 149b750df7e8
Revises:
Create Date: 2025-09-08 13:32:22.284697

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "149b750df7e8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agencies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "cfda_programs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("number"),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("state_code", sa.String(), nullable=True),
        sa.Column("opportunity_number", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "forecasted",
                "posted",
                "closed",
                "archive",
                name="opportunity_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("fiscal_year", sa.Integer(), nullable=True),
        sa.Column("post_date", sa.Date(), nullable=True),
        sa.Column("est_post_date", sa.Date(), nullable=True),
        sa.Column("close_date", sa.Date(), nullable=True),
        sa.Column("award_date", sa.Date(), nullable=True),
        sa.Column("award_ceiling", sa.Integer(), nullable=True),
        sa.Column("award_floor", sa.Integer(), nullable=True),
        sa.Column("total_funding_amount", sa.Integer(), nullable=True),
        sa.Column("number_of_awards", sa.Integer(), nullable=True),
        sa.Column("eligibility", sa.Text(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("contact_name", sa.String(), nullable=True),
        sa.Column("contact_email", sa.String(), nullable=True),
        sa.Column("contact_phone", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("extra", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_number"),
    )
    op.create_table(
        "opportunity_agency",
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("agency_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"],
            ["agencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "agency_id"),
    )
    op.create_table(
        "opportunity_cfda",
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("cfda_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cfda_id"],
            ["cfda_programs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("opportunity_id", "cfda_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("opportunity_cfda")
    op.drop_table("opportunity_agency")
    op.drop_table("opportunities")
    op.drop_table("cfda_programs")
    op.drop_table("agencies")
    # ### end Alembic commands ###
