"""added funding type col

Revision ID: 1f57155ad91e
Revises: 590889abf1b7
Create Date: 2025-10-19 20:52:51.805833

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f57155ad91e'
down_revision = '590889abf1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    funding_type_enum = postgresql.ENUM('state', 'federal', 'local', 'private', name='funding_type_enum')
    funding_type_enum.create(op.get_bind())
    
    # Then add the column using the enum type
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funding_type', sa.Enum('state', 'federal', 'local', 'private', name='funding_type_enum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('funding_type')
    
    # Then drop the enum type
    funding_type_enum = postgresql.ENUM('state', 'federal', 'local', 'private', name='funding_type_enum')
    funding_type_enum.drop(op.get_bind())

    # ### end Alembic commands ###
