"""Added rfp_url col

Revision ID: 3b5975f4e5aa
Revises: 0f999a6d2e4a
Create Date: 2025-10-28 18:20:06.902731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b5975f4e5aa'
down_revision = '0f999a6d2e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rfp_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('rfp_url')

    # ### end Alembic commands ###
