"""Updated base grant schema

Revision ID: 527e2597a2f3
Revises: 61d32d520c78
Create Date: 2025-09-28 19:08:57.481238

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "527e2597a2f3"
down_revision = "61d32d520c78"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunity_agency") as batch_op:
        batch_op.drop_constraint(
            "opportunity_agency_agency_id_fkey", type_="foreignkey"
        )
    op.drop_table("opportunity_agency")
    op.drop_table("opportunity_cfda")
    op.drop_table("agencies")
    op.drop_table("cfda_programs")
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_grant_id", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("agency", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("funding_instrument", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("archive_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("cost_sharing", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("award_max", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("award_min", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("eligibility_summary", sa.String(), nullable=True)
        )
        batch_op.add_column(sa.Column("attachments", sa.JSON(), nullable=True))
        batch_op.drop_column("est_post_date")
        batch_op.drop_column("award_ceiling")
        batch_op.drop_column("award_date")
        batch_op.drop_column("award_floor")
        batch_op.drop_column("opportunity_number")
        batch_op.drop_column("version")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "opportunity_number", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("award_floor", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("award_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("award_ceiling", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("est_post_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("attachments")
        batch_op.drop_column("eligibility_summary")
        batch_op.drop_column("award_min")
        batch_op.drop_column("award_max")
        batch_op.drop_column("cost_sharing")
        batch_op.drop_column("archive_date")
        batch_op.drop_column("funding_instrument")
        batch_op.drop_column("agency")
        batch_op.drop_column("source_grant_id")

    op.create_table(
        "opportunity_cfda",
        sa.Column("opportunity_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("cfda_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["cfda_id"], ["cfda_programs.id"], name="opportunity_cfda_cfda_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name="opportunity_cfda_opportunity_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "cfda_id", name="opportunity_cfda_pkey"
        ),
    )
    op.create_table(
        "cfda_programs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="cfda_programs_pkey"),
        sa.UniqueConstraint("number", name="cfda_programs_number_key"),
    )
    op.create_table(
        "opportunity_agency",
        sa.Column("opportunity_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("agency_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["agency_id"], ["agencies.id"], name="opportunity_agency_agency_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name="opportunity_agency_opportunity_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "opportunity_id", "agency_id", name="opportunity_agency_pkey"
        ),
    )
    op.create_table(
        "agencies",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "source",
            sa.VARCHAR(),
            server_default=sa.text("'grants.gov'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="agencies_pkey"),
    )
    # ### end Alembic commands ###
