"""Added raw_text and content_hash

Revision ID: 590889abf1b7
Revises: 6154046fb916
Create Date: 2025-10-17 14:40:08.088725

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '590889abf1b7'
down_revision = '6154046fb916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('content_hash')
        batch_op.drop_column('raw_text')

    # ### end Alembic commands ###
