"""Recreate opportunities table

Revision ID: 6154046fb916
Revises: 6978174896e7
Create Date: 2025-10-04 12:25:08.097539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6154046fb916'
down_revision = '6978174896e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('source_grant_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('forecasted', 'posted', 'closed', 'archive', name='opportunity_status_enum'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_summary', sa.String(), nullable=True),
    sa.Column('agency', sa.String(), nullable=True),
    sa.Column('funding_instrument', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('archive_date', sa.Date(), nullable=True),
    sa.Column('cost_sharing', sa.Boolean(), nullable=True),
    sa.Column('award_max', sa.Integer(), nullable=True),
    sa.Column('award_min', sa.Integer(), nullable=True),
    sa.Column('total_funding_amount', sa.Integer(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('eligibility_summary', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    # ### end Alembic commands ###
