"""updated agencies to have source

Revision ID: 61d32d520c78
Revises: 8fca6651f23c
Create Date: 2025-09-09 00:00:06.736582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d32d520c78'
down_revision = '8fca6651f23c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), nullable=False, server_default='grants.gov'))
        batch_op.drop_constraint(batch_op.f('agencies_code_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('agencies_code_key'), ['code'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###
