"""added relevance_score in opportunity table

Revision ID: 6978174896e7
Revises: a56d262ecdf3
Create Date: 2025-10-04 12:20:09.101334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6978174896e7'
down_revision = 'a56d262ecdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('forecasted', 'posted', 'closed', 'archive', name='opportunity_status_enum'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('close_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_funding_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eligibility', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('source_grant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('agency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('funding_instrument', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('archive_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('cost_sharing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('award_max', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('award_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('eligibility_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description_summary', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='opportunities_pkey')
    )
    # ### end Alembic commands ###
