"""allowed opportunity_num to not be unique as ids change across grant sources

Revision ID: 8fca6651f23c
Revises: 149b750df7e8
Create Date: 2025-09-08 23:53:11.685808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fca6651f23c'
down_revision = '149b750df7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('opportunities_opportunity_number_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('opportunities_opportunity_number_key'), ['opportunity_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
