"""added is_recurring and application_instructions columns

Revision ID: 96ebf6cf7a06
Revises: 7fee2305f8af
Create Date: 2025-11-03 21:53:35.733506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96ebf6cf7a06'
down_revision = '7fee2305f8af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_recurring', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('application_instructions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_column('application_instructions')
        batch_op.drop_column('is_recurring')

    # ### end Alembic commands ###
