"""removed num of awards column

Revision ID: a56d262ecdf3
Revises: 527e2597a2f3
Create Date: 2025-09-28 21:04:44.842407

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a56d262ecdf3"
down_revision = "527e2597a2f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description_summary", sa.String(), nullable=True)
        )
        batch_op.alter_column(
            "source_grant_id", existing_type=sa.VARCHAR(), nullable=False
        )
        batch_op.drop_column("number_of_awards")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("opportunities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "number_of_awards", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "source_grant_id", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_column("description_summary")

    # ### end Alembic commands ###
